"""add aiinteraction model

Revision ID: 8f5559279b76
Revises: 931e7511646a
Create Date: 2025-03-24 04:27:39.151156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5559279b76'
down_revision = '931e7511646a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # with op.batch_alter_table('entries', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # with op.batch_alter_table('entry_goals', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'entries', ['entry_id'], ['id'])
    #     batch_op.create_foreign_key(None, 'goals', ['goal_id'], ['id'])

    # with op.batch_alter_table('entry_tags', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'tags', ['tag_id'], ['id'])
    #     batch_op.create_foreign_key(None, 'entries', ['entry_id'], ['id'])

    # with op.batch_alter_table('goals', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # with op.batch_alter_table('milestones', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'goals', ['goal_id'], ['id'])
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('milestones', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')

    # with op.batch_alter_table('goals', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    # with op.batch_alter_table('entry_tags', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')

    # with op.batch_alter_table('entry_goals', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')

    # with op.batch_alter_table('entries', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('ai_interactions')
    # ### end Alembic commands ###
